### ISSUE TITLE
Push issue

### ISSUE THREAD

**Issue by mspector13** [ecoquants/findinghal#12]
This problem has been intermittent, but persistent. Lately, I have not been able to push commits to this repo: 

<img width="869" alt="Screen Shot 2022-06-03 at 11 11 05 AM" src="https://user-images.githubusercontent.com/59982410/171922071-99888c51-c8f4-4ce1-9ba1-60a9e985493a.png">

I'm basically stuck here forever. [This article](https://community.rstudio.com/t/rstudio-stuck-loading-push-to-git/109472/2) might be relevant, but I don't want to mess with SSH keys without prior approval

**Comment by bbest** [comment]
When this happens, I recommend trying `git` commands in the Terminal:

```
git status

git push
```

It's more responsive and verbose.

**Comment by bbest** [comment]
* [Chapter 9 Personal access token for HTTPS | Happy Git and GitHub for the useR](https://happygitwithr.com/https-pat.html#pat-troubleshooting)

**Comment by bbest** [comment]
Per [Git push hangs when pushing to Github? - Stack Overflow](https://stackoverflow.com/questions/16906161/git-push-hangs-when-pushing-to-github), try stopping the Terminal process that is hung and run this in a new Terminal:

```bash
git config --global core.askpass "git-gui--askpass"
```

**Comment by bbest** [comment]
So the problem was files over 100MB:

<img width="142" alt="image" src="https://user-images.githubusercontent.com/2837257/171930455-45b16436-21f9-44ff-9816-7c36c39ad23e.png">

So reviewed:

* [Managing large files - GitHub Docs](https://docs.github.com/en/repositories/working-with-files/managing-large-files)
* [BFG Repo-Cleaner by rtyley](https://rtyley.github.io/bfg-repo-cleaner/)
* [Download Java for macOS](https://java.com/en/download/)

And ran:

```bash
java -jar bfg.jar --strip-blobs-bigger-than 100M
```
